$(document).ready(function(){
    $("#bContacto").click(function(){
        $('#contacto').addClass('active');
    });
    $("#bPropiedades").click(function(){
        $('#propiedades').addClass('active');
    });
    $("#bInicio").click(function(){
        $(window).scrollTop($('#dvideo').offset().top);
        $('#dvideo').addClass('active');
    });
    });
});
