$(document).ready(function(){
    $("#bContacto").click(function(){
        $('#bContacto').addClass('active');
        $('#bPropiedades').remove('active');
        $('#bInicio').remove('active');
    });
    $("#bPropiedades").click(function(){
        $('#bPropiedades').addClass('active');
        $('#bContacto').remove('active');
        $('#bInicio').remove('active');
    });
    $("#bInicio").click(function(){
        $(window).scrollTop($('#dvideo').offset().top);
        $('#bInicio').addClass('active');
        $('#bContacto').remove('active');
        $('#bPropiedades').remove('active');
    });
    });
});
